services:
  - type: web
    name: laravel-breeze-app
    env: docker
    buildCommand: "docker build -t laravel-breeze-app ."
    startCommand: "docker run -p 8080:80 --log-driver json-file laravel-breeze-app"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:xL42zCmPgIDK69zKZyCOKsqCbVDqgpqp6Z+dhmqpZPs=
      - key: APP_DEBUG
        value: "true"
      - key: APP_URL
        value: https://mini-twitter-rc3g.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-cgg730o2qv28tc2e68ig-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: twitter_ll2x
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: 0amAVF05UAi7sk0iBIXhdp56t3vNKxFg
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: debug
      - key: LOG_DEPRECATIONS_CHANNEL
        value: null

databases:
  - name: mini-twitter
    engine: postgres
    version: "15"
    username: root
    password: 0amAVF05UAi7sk0iBIXhdp56t3vNKxFg
    port: 5432
    database: twitter_ll2x
